name: flutter_application_demo
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  # sdk: '>=3.1.0 <4.0.0'
  sdk: '>=3.2.5 <4.0.0'

# dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  intl_utils: ^2.8.5

  # Dio
  dio: ^5.4.3+1
  pretty_dio_logger: ^1.3.1
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_hive_store: ^3.2.2

  # Network
  url_launcher: ^6.2.6
  connectivity_plus: ^6.0.3
  # webview_flutter: ^4.7.0

  # Storage
  get_storage: ^2.1.1
  flutter_secure_storage: ^9.1.1

  # Tool
  get_it: ^7.6.7
  equatable: ^2.0.5
  flutter_hooks: ^0.20.5
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1

  # State Management
  hooks_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Permission
  permission_handler: ^11.3.1

  # Files
  path: ^1.8.3
  path_provider: ^2.1.3
  cached_network_image: ^3.3.1

  # UI
  flutter_svg: ^2.0.10+1
  go_router: ^14.1.0
  
  # cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  custom_lint: ^0.6.4
  flutter_lints: ^3.0.2 
  build_runner: ^2.4.9
  riverpod_lint: ^2.3.10
  riverpod_generator: ^2.4.0
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

